apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: prom-metric-demo
    name: prom-metric-demo
    namespace: prophet
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prom-metric-demo
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: prom-metric-demo
        name: prom-metric-demo
      spec:
        nodeSelector:
          prophet.4paradigm.com/system: "true"
        containers:
        - env:
          - name: MY_MEM_REQUEST
            valueFrom:
              resourceFieldRef:
                containerName: app
                resource: requests.memory
          - name: MY_MEM_LIMIT
            value: "1024"
          image: docker-search.4pd.io/prom-metric-demo:1.0
          imagePullPolicy: IfNotPresent
          name: app
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/prometheus
              port: 51088
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/prometheus
              port: 51088
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "512Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: app-logs
            mountPath: /app/logs
          workingDir: /app
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: docker-secret
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: app-logs
          emptyDir: {}
